# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
os: linux
dist: xenial
cache: packages
r:
  - oldrel
  - release
  - devel
before_install:
  - sudo apt-get update -qq
